extends: stylelint-config-standard
rules:
  string-quotes: single
  selector-list-comma-newline-after: never-multi-line
  selector-list-comma-space-after: always
  # no-descending-specificity: null
  # rule-empty-line-before:
  #   - always
  #   - except: first-nested
