default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: ivy_development

test:
  <<: *default
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  database: ivy_test
  password: <%= ENV.fetch('RDS_PASSWORD') %>

production:
  <<: *default
  host: <%= ENV.fetch('RDS_HOSTNAME') %>
  database: <%= ENV.fetch('RDS_DB_NAME') %>
  username: <%= ENV.fetch('RDS_USERNAME') %>
  password: <%= ENV.fetch('RDS_PASSWORD') %>
