name: Deploy Production
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@master

      - name: Download Latest ECS Task Definition
        run: aws ecs describe-task-definition --task-definition ivy-production --query taskDefinition > task-definition.json

      - name: Render the new ECS Web Task Definition
        id: render-web-task-definition-production
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ivy-production-web
          image: ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }}

      - name: Render the new ECS Worker Task Definition
        id: render-worker-task-definition-production
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-task-definition-production.outputs.task-definition }}
          container-name: ivy-production-worker
          image: ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }}

      - name: Deploy the Task Definition to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-worker-task-definition-production.outputs.task-definition }}
          service: ivy-production
          cluster: ivy-production
          wait-for-service-stability: true
          wait-for-minutes: 6
