name: Verify
on: [push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
      - name: Restore gems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install gems
        run: bundle install --deployment --jobs 4

      - name: Setup node
        uses: actions/setup-node@v1
      - name: Find yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install --pure-lockfile

      - name: Ruby linter
        run: bundle exec rubocop --parallel
      - name: ERB linter
        run: bundle exec erblint --lint-all
      - name: JS linter
        run: yarn lint:js
      - name: SCSS linter
        run: yarn lint:scss

      - name: Static code analysis
        run: bundle exec brakeman -q
      - name: Ruby dependencies vulnerabilities check
        run: bundle exec bundle-audit check --update
      - name: JS dependencies vulnerabilities check
        run: yarn audit

  # tests:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:11
  #       env:
  #         POSTGRES_USER: myapp
  #         POSTGRES_DB: myapp_test
  #         POSTGRES_PASSWORD: ""
  #       ports: ["5432:5432"]
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #     - name: Ruby gem cache
  #       uses: actions/cache@v1
  #       with:
  #         path: vendor/bundle
  #         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-
  #     - name: Install gems
  #       run: |
  #         bundle config path vendor/bundle
  #         bundle install --jobs 4 --retry 3
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.13.0
  #     - name: Find yarn cache location
  #       id: yarn-cache
  #       run: echo "::set-output name=dir::$(yarn cache dir)"
  #     - name: JS package cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ${{ steps.yarn-cache.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-
  #     - name: Install packages
  #       run: |
  #         yarn install --pure-lockfile
  #
  #     - name: Setup test database
  #       env:
  #         RAILS_ENV: test
  #         PGHOST: localhost
  #         PGUSER: myapp
  #       run: |
  #         bin/rails db:setup
  #
  #     - name: Run tests
  #       run: bin/rspec
